FROM python:3.12-slim

ARG PLAYLISTMUSE_VERSION=dev
ARG PLAYLISTMUSE_CHANNEL=dev
ARG PLAYLISTMUSE_GIT_SHA=unknown
ARG PLAYLISTMUSE_GIT_DIRTY=false

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PLAYLISTMUSE_DATA_DIR=/app/data \
    PLAYLISTMUSE_VERSION=${PLAYLISTMUSE_VERSION} \
    PLAYLISTMUSE_CHANNEL=${PLAYLISTMUSE_CHANNEL} \
    PLAYLISTMUSE_GIT_SHA=${PLAYLISTMUSE_GIT_SHA} \
    PLAYLISTMUSE_GIT_DIRTY=${PLAYLISTMUSE_GIT_DIRTY}

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend backend
COPY frontend frontend
COPY quality quality
RUN mkdir -p data

EXPOSE 5780
CMD ["uvicorn", "backend.application:app", "--host", "0.0.0.0", "--port", "5780"]
